### ISSUE TITLE
Dockbix-db-storage won´t start - STATUS: Exited (0)

### ISSUE THREAD

**Issue by C4lp4s** [zabbix/zabbix-community-docker#106]
### Description

Dockbix-db-storage won´t start. I have used the following compose file:
```

version: '2'
services:
  zabbix-db-storage:
    image: busybox:latest
    volumes:
      - /var/lib/mysql
  zabbix-db:
    image: monitoringartist/zabbix-db-mariadb
    volumes:
      - /backups:/backups
      - /etc/localtime:/etc/localtime:ro
    volumes_from:
      - zabbix-db-storage
    environment:
      - MARIADB_USER=mariadbuser
      - MARIADB_PASS=***
  zabbix-server:
    image: monitoringartist/dockbix-xxl:latest
    ports:
      - "8090:80"
      - "10051:10051"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    links:
      - zabbix-db:zabbix.db
    environment:
      - ZS_DBHost=zabbix.db
      - ZS_DBUser=mariadbuser
      - ZS_DBPassword=***
```

### What i have done

1. Created the compose file and named it "docker-compose.yml"
2. Started it with "sudo docker-compuse up -d"
3. Saw that every container expect the Dockbix-db-storage is running.

### You Docker knowledge level

I´m new to Docker :)

King regards
