### ISSUE TITLE
Zabbix failing to start in Kubernetes

### ISSUE THREAD

**Issue by asc-adean** [zabbix/zabbix-community-docker#122]
### Description

Zabbix seems to be doing some string replacement and it's failing during startup

### Steps to Reproduce

1. Apply zabbix deployment config
2. Watch as the pod never comes online

**Expected behavior:** Zabbix comes online
**Actual behavior:** Log output:
```
?[1m?[32m2019-03-19 20:01:11,000 INFO?(B?[m Nginx status page: allowed address set to 127.0.0.1.
?[1m?[32m2019-03-19 20:01:11,000 INFO?(B?[m PHP-FPM status page: allowed address set to 127.0.0.1.
?[1m?[32m2019-03-19 20:01:11,000 INFO?(B?[m Preparing XXL features
?[1m?[32m2019-03-19 20:01:11,000 INFO?(B?[m XXL configuration done.
?[1m?[32m2019-03-19 20:01:11,000 INFO?(B?[m Waiting for API, it's still not available
?[1m?[32m2019-03-19 20:01:11,000 INFO?(B?[m Preparing server configuration
sed: -e expression #1, char 37: unknown option to `s'
```

**Reproduces how often:** Every time

### Versions

Kubernetes v1.11.5

### Additional Information

Environment vars being passed:

```
          env:
            - name: ZS_DBPassword
              valueFrom:
                secretKeyRef:
                  name: zabbix-secrets
                  key: MYSQL_ROOT_PASSWORD
            - name: ZS_DBHost
              value: ZABBIX_MYSQL_SERVICE
            - name: ZS_DBUser
              value: "root"
            - name: ZS_enabled
              value: "true"
            - name: ZW_enabled
              value: "true"
            - name: ZA_enabled
              value: "true"
```
### You Docker knowledge level

High

**Comment by jangaraj** [comment]
It is not clear, which image:tag did you use. Could you provide this detail, please?

**Comment by asc-adean** [comment]
Sorry, I am using `monitoringartist/dockbix-xxl:latest`

**Comment by asc-adean** [comment]
This is the entire deployment yaml:

```
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: zabbix
  name: zabbix
  namespace: operations
spec:
  selector:
    matchLabels:
      app: zabbix
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: zabbix
      name: zabbix
    spec:
      containers:
        - name: zabbix
          image: monitoringartist/dockbix-xxl:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: web
            - containerPort: 10051
              name: agent
          env:
            - name: ZS_DBPassword
              valueFrom:
                secretKeyRef:
                  name: zabbix-secrets
                  key: MYSQL_ROOT_PASSWORD
            - name: ZS_DBHost
              value: "zabbix-mysql.operations"
            - name: ZS_DBUser
              value: "root"
            - name: ZS_enabled
              value: "true"
            - name: ZW_enabled
              value: "true"
            - name: ZA_enabled
              value: "true"
```

I decided to use the Kubernetes DNS for mysql, that was the only thing I changed from the first post
