### ISSUE TITLE
App fails to start with docker-compose

### ISSUE THREAD

**Issue by mlschuh** [zabbix/zabbix-community-docker#62]
Hi there,

I'm unable to reliably get the service to come up when using docker-compose. The first time I attempt to start, the server gets stuck with the following:

```
zabbix-db_1      | 
zabbix-db_1      | Creating DB admin user...
zabbix-db_1      | 
zabbix-db_1      | => Creating MariaDB user 'zabbix' with 'adminm3' password.
zabbix-db_1      |     ========================================================================
zabbix-db_1      |     You can now connect to this MariaDB Server using:                   
zabbix-db_1      |     mysql -uzabbix -padminm3 -h<host>                      
zabbix-db_1      |                                                                         
zabbix-db_1      |     For security reasons, you might want to change the above password.  
zabbix-db_1      |     The 'root' user has no password but only allows local connections   
zabbix-db_1      |     ========================================================================
zabbix-server_1  | [LOG 01:05:55] Waiting for API, it's still not available
zabbix-server_1  | [LOG 01:05:56] Database server is available
zabbix-server_1  | [LOG 01:05:56] Checking if database exists or SQL import is required
zabbix-server_1  | [WARNING 01:05:56] Zabbix database doesn't exist. Installing and importing default settings
zabbix-server_1  | [LOG 01:05:56] Database and user created, importing default SQL
zabbix-server_1  | [LOG 01:06:00] Waiting for API, it's still not available
zabbix-server_1  | [LOG 01:06:05] Waiting for API, it's still not available
zabbix-server_1  | [LOG 01:06:10] Waiting for API, it's still not available
zabbix-server_1  | [LOG 01:06:15] Waiting for API, it's still not available
```

If I take it down and then bring it back up, the app server keeps respawning with the following and never comes up properly:

```
zabbix-server_1  | Starting Zabbix Server. Zabbix 3.0.4 (2016-08-25) (revision 61185).
zabbix-server_1  | Press Ctrl+C to exit.
zabbix-server_1  | 
zabbix-server_1  |    422:20160902:010959.074 Starting Zabbix Server. Zabbix 3.0.4 (2016-08-25) (revision 61185).
zabbix-server_1  | 
zabbix-server_1  | 2016-09-02 01:09:59,075 DEBG 'zabbix-server' stdout output:
zabbix-server_1  |    422:20160902:010959.075 ****** Enabled features ******
zabbix-server_1  |    422:20160902:010959.075 SNMP monitoring:           YES
zabbix-server_1  |    422:20160902:010959.075 IPMI monitoring:           YES
zabbix-server_1  |    422:20160902:010959.075 Web monitoring:            YES
zabbix-server_1  | 
zabbix-server_1  | 2016-09-02 01:09:59,076 DEBG 'zabbix-server' stdout output:
zabbix-server_1  |    422:20160902:010959.075 VMware monitoring:         YES
zabbix-server_1  |    422:20160902:010959.075 SMTP authentication:       YES
zabbix-server_1  |    422:20160902:010959.075 Jabber notifications:      YES
zabbix-server_1  |    422:20160902:010959.075 Ez Texting notifications:  YES
zabbix-server_1  |    422:20160902:010959.075 ODBC:                      YES
zabbix-server_1  |    422:20160902:010959.075 SSH2 support:              YES
zabbix-server_1  |    422:20160902:010959.075 IPv6 support:              YES
zabbix-server_1  |    422:20160902:010959.075 TLS support:               YES
zabbix-server_1  |    422:20160902:010959.075 ******************************
zabbix-server_1  |    422:20160902:010959.075 using configuration file: /usr/local/etc/zabbix_server.conf
zabbix-server_1  | 
zabbix-server_1  | 2016-09-02 01:09:59,081 DEBG 'zabbix-server' stdout output:
zabbix-server_1  |    422:20160902:010959.081 cannot use database "zabbix": Zabbix server cannot work with a Zabbix proxy database
zabbix-server_1  | 
zabbix-server_1  | 2016-09-02 01:10:00,086 INFO success: zabbix-server entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
zabbix-server_1  | 2016-09-02 01:10:01,088 DEBG fd 19 closed, stopped monitoring <POutputDispatcher at 41009096 for <Subprocess at 40435512 with name zabbix-server in state RUNNING> (stdout)>
zabbix-server_1  | 2016-09-02 01:10:01,088 DEBG fd 25 closed, stopped monitoring <POutputDispatcher at 41008952 for <Subprocess at 40435512 with name zabbix-server in state RUNNING> (stderr)>
zabbix-server_1  | 2016-09-02 01:10:01,088 INFO exited: zabbix-server (exit status 232; not expected)
zabbix-server_1  | 2016-09-02 01:10:01,089 DEBG received SIGCLD indicating a child quit
zabbix-server_1  | 2016-09-02 01:10:02,098 INFO spawned: 'zabbix-server' with pid 425
zabbix-server_1  | 2016-09-02 01:10:02,120 DEBG 'zabbix-server' stdout output:
zabbix-server_1  | Starting Zabbix Server. Zabbix 3.0.4 (2016-08-25) (revision 61185).
```

Here is the compose file that I'm working with. Running the latest version of Docker for Mac, 1.12.1-beta24. Also had very similar issues with it in Ubuntu. I've also attempted to use the (only slightly different) docker-compose file from the repo to the same result.

```
version: "2"
services:
    zabbix-db:
      image: zabbix/zabbix-db-mariadb
      volumes:
        - zabbix_backups:/backups
        - /etc/localtime:/etc/localtime:ro
        - zabbix_db_storage:/var/lib/mysql
      environment:
        - MARIADB_USER=zabbix
        - MARIADB_PASS=adminm3
      restart: always

    zabbix-server:
      image: monitoringartist/zabbix-3.0-xxl:latest
      ports:
        - "8085:80"
        - "10051:10051"
      volumes:
        - /etc/localtime:/etc/localtime:ro
      links:
        - zabbix-db:zabbix.db
      environment:
        - ZS_DBHost=zabbix.db
        - ZS_DBUser=zabbix
        - ZS_DBPassword=adminm3
        - ZS_StartVMwareCollectors=1
        - ZS_StartIPMIPollers=3
        - XXL_grapher=true
        - XXL_analytics=false
      restart: always

volumes:
    zabbix_db_storage:
        driver: local
    zabbix_backups:
        driver: local
```

Hopefully someone with a bit more direct experience with these repos can help provide some insight. 

-Mitch
