### ISSUE TITLE
startup takes several minutes for zabbix-xxl:latest

### ISSUE THREAD

**Issue by white-hat** [zabbix/zabbix-community-docker#66]
I'm using such docker-compose configuration to launch zabbix backend service

```
zabbix-backend:
  image: monitoringartist/zabbix-xxl:latest
  mem_limit: 4294967296
  ports:
    - "10051:10051"
  volumes:
    - /etc/localtime:/etc/localtime:ro
  environment:
    - XXL_api=false
    - XXL_searcher=false
    - XXL_analytics=false
    - ZW_enabled=false
    - ZS_DBHost=*******
    - ZS_DBUser=zabbix
    - ZS_DBPassword=********
    - ZA_Hostname=Zabbix BackEnd
    - ZS_CacheSize=128M
    - ZS_StartDBSyncers=4
    - ZS_StartPollers=256
    - ZS_StartPollersUnreachable=8
    - ZS_HistoryCacheSize=16M
    - ZS_TrendCacheSize=16M
    - ZS_ValueCacheSize=48M
```

It takes up to 5 minutes for this container to start, and I see these errors while it's starting

```
zabbix-backend_1   | [LOG 20:13:19] Waiting for API, it's still not available
zabbix-backend_1   | [LOG 20:13:24] Waiting for API, it's still not available
zabbix-backend_1   | [LOG 20:13:29] Waiting for API, it's still not available
zabbix-backend_1   | [LOG 20:13:34] Waiting for API, it's still not available
zabbix-backend_1   | [LOG 20:13:39] Waiting for API, it's still not available
```

Can I somehow really disable that API calls?
