### ISSUE TITLE
Setup an instance with ZJ_enabled requires more configuration that someone would expect

### ISSUE THREAD

**Issue by Guibod** [zabbix/zabbix-community-docker#74]
If you put a `ZJ_enabled='true'` env variable you still need to specify 3 items in order for it to work with the server. If not, zabbix don't know its javagateway.

Exerpt from my ansible config:
```
      env:
        ZS_DBHost: zabbix.db
        ZS_DBUser: zabbix
        ZS_DBPassword: "password"
        ZJ_enabled: "true"
        ZS_StartJavaPollers: 3
        ZS_JavaGateway: "127.0.0.1"
        ZS_JavaGatewayPort: 10052
```

The last 3 lines are required, and never defaulted by the presence of a `ZJ_enabled`.
I do understand that you may want to start a container running only the JavaGateway and that it is important to allow very specific configuration. Yet, i think that most users of this docker image like me, wants to enable JavaGateway as simply as possible, and that may be the purpose of ZJ_enabled.

My suggestion: default those 3 ENV variables to a conservative value (why not above values) if `ZJ_enabled` is true and if they are missing.
