### ISSUE TITLE
MariaDB does not start

### ISSUE THREAD

**Issue by paulz1** [zabbix/zabbix-community-docker#84]
I did `docker pull monitoringartist/zabbix-db-mariadb` today...
Then MariaDB could not start now.
I'm not sure it's because of pulling of new image, as there was a problem with running container even before pull.

This is an error.log from MariaDb container :

> 170418 10:47:03 [Note] /usr/sbin/mysqld (mysqld 10.0.30-MariaDB) starting as process 254 ...
> 170418 10:47:03 [Warning] Could not increase number of max_open_files to more than 4096 (request: 4407)
> 170418 10:47:03 [Note] InnoDB: Using mutexes to ref count buffer pool pages
> 170418 10:47:03 [Note] InnoDB: The InnoDB memory heap is disabled
> 170418 10:47:03 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
> 170418 10:47:03 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
> 170418 10:47:03 [Note] InnoDB: Compressed tables use zlib 1.2.7
> 170418 10:47:03 [Note] InnoDB: Using Linux native AIO
> 170418 10:47:03 [Note] InnoDB: Using CPU crc32 instructions
> 170418 10:47:03 [Note] InnoDB: Initializing buffer pool, size = 768.0M
> 170418 10:47:03 [Note] InnoDB: Completed initialization of buffer pool
> 170418 10:47:03 [ERROR] InnoDB: ./ibdata1 can't be opened in read-write mode
> 170418 10:47:03 [ERROR] InnoDB: The system tablespace must be writable!
> 170418 10:47:03 [ERROR] Plugin 'InnoDB' init function returned error.
> 170418 10:47:03 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
> 170418 10:47:03 [ERROR] Failed to initialize plugins.
> 170418 10:47:03 [ERROR] Aborting

Does the message about "`Could not increase number of max_open_files to more than 4096 (request: 4407)`" is important. 
I thought that it could explain the problem, but it's just marked as Warning.

And, if not... what could explain the problem with "./ibdata1"?
This is a part of compose file :
```

zabbix-db-storage:
  image: busybox:latest
  volumes:
    - /var/lib/mysql

zabbix-db:
  image: monitoringartist/zabbix-db-mariadb
  volumes:
    - /backups:/backups
  volumes_from:
    - zabbix-db-storage
```
